# name: next-car-backend.js CI

# on:
#   push:
#     branches: [ main ]

# jobs: 
#   builds: 
#     runs-on: self-hosted
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: 
#         npm i
name: NextCar backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      env:
        PORT: ${{ secrets.PORT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_HOST_PASSWORD: ${{ secrets.DB_HOST_PASSWORD }}
        DB_DIALECT: ${{ secrets.DB_DIALECT }}
        FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: cd db/ && npm run migrate && cd ../
    - run: NODE_ENV=production npm start