name: NextCar backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    
    env:
      PORT: ${{ secrets.PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_HOST_PASSWORD: ${{ secrets.DB_HOST_PASSWORD }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DB_PORT: ${{ secrets.DB_PORT }}
      FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Create env file
      run: |
        touch .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_USER=${{ secrets.DB_USER }} >> .env
        echo DB_DIALECT=${{ secrets.DB_DIALECT }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo FRONTEND_ORIGIN=${{ secrets.FRONTEND_ORIGIN }} >> .env
    - run: cd db/ && npm run migrate && cd ../
    - run: pm2 stop 0
    - run: pm2 start 0
    - run: pm2 save
    - run: sudo service nginx restart