name: NextCar backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    
    env:
      PORT: ${{ secrets.PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_HOST_PASSWORD: ${{ secrets.DB_HOST_PASSWORD }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DB_PORT: ${{ secrets.DB_PORT }}
      FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: cd db/ && npm run migrate && cd ../
    - run: NODE_ENV=production npm start